import { Route } from "react-router-dom"
import {TheSmartestWebsite, MeasureYourLife, TheMiracleYear, BettingOnUnknownUnknowns, LessonsOnProductMarketFit, DiversificationResultsInMediocrity, PricingNicheProducts,
        TheGreatUPS, OnlyThingThatMatters, MasterPlanTesla, SurvivorIoCaseStudy, YoutubeCoolhunters, BattlePasses, TimSweeneyTalks, TimeAnxiety, ImpossiblyUseless, GotMyBrainBack, 
        InternetHasBroadenedCareer, ThePonziCareer, SpeculationIsASuperpower, StartupIdeasDumbest, YourIdeaIsWorthless, TheDayOneFan, TheSUPREMEBranding, AdviceForAmbitious, NobodyCares, 
        BettingTheFirm, TheFactorioMindset, CovidStoleOurTime, CloneCulture, CompetingToWinDeals, SoftLaunchAMobileGame, LessonsFromYear29, VentureCapitalInWeb3, DecadesAreShort, ReturnToFundamentals, 
        TheCurrentThing, CryptoGamingIsNotTheFuture, SeeingOnlyTheQuestions, InsideFacebookMarketplace, MentalModelExamples, Soulbound, TeslaMasterPlan, UserEngagement, ZhangYiming} from "./ArticleComponents22"
import { SortByControversial, TheStoryOfTFT } from "./ArticleComponents23"


export default  [
    <Route path="MeasureYourLife" element={<MeasureYourLife />} key="MeasureYourLife" />,
    <Route path="TheMiracleYear" element={<TheMiracleYear />} key="TheMiracleYear" />,
    <Route path="BettingOnUnknownUnknowns" element={<BettingOnUnknownUnknowns />} key="BettingOnUnknownUnknowns" />,
    <Route path="LessonsOnProductMarketFit" element={<LessonsOnProductMarketFit />} key="LessonsOnProductMarketFit" />,
    <Route path="DiversificationResultsInMediocrity" element={<DiversificationResultsInMediocrity />} key="DiversificationResultsInMediocrity" />,
    <Route path="PricingNicheProducts" element={<PricingNicheProducts />} key="PricingNicheProducts" />,
    <Route path="TheGreatUPS" element={<TheGreatUPS />} key="TheGreatUPS" />,
    <Route path="OnlyThingThatMatters" element={<OnlyThingThatMatters />} key="OnlyThingThatMatters" />,
    <Route path="MasterPlanTesla" element={<MasterPlanTesla />} key="MasterPlanTesla" />,
    <Route path="SurvivorIoCaseStudy" element={<SurvivorIoCaseStudy />} key="SurvivorIoCaseStudy" />,
    <Route path="YoutubeCoolhunters" element={<YoutubeCoolhunters />} key="YoutubeCoolhunters" />,
    <Route path="TheSmartestWebsite" element={<TheSmartestWebsite />} key="TheSmartestWebsite" />,
    <Route path="BattlePasses" element={<BattlePasses />} key="BattlePasses" />,
    <Route path="TimSweeneyTalks" element={<TimSweeneyTalks />} key="TimSweeneyTalks" />,
    <Route path="TimeAnxiety" element={<TimeAnxiety />} key="TimeAnxiety" />,
    <Route path="ImpossiblyUseless" element={<ImpossiblyUseless />} key="ImpossiblyUseless" />,
    <Route path="GotMyBrainBack" element={<GotMyBrainBack />} key="GotMyBrainBack" />,
    <Route path="InternetHasBroadenedCareer" element={<InternetHasBroadenedCareer />} key="InternetHasBroadenedCareer" />,
    <Route path="ThePonziCareer" element={<ThePonziCareer />} key="ThePonziCareer" />,
    <Route path="SpeculationIsASuperpower" element={<SpeculationIsASuperpower />} key="SpeculationIsASuperpower" />,
    <Route path="StartupIdeasDumbest" element={<StartupIdeasDumbest />} key="StartupIdeasDumbest" />,
    <Route path="YourIdeaIsWorthless" element={<YourIdeaIsWorthless />} key="YourIdeaIsWorthless" />,
    <Route path="TheDayOneFan" element={<TheDayOneFan />} key="TheDayOneFan" />,
    <Route path="TheSUPREMEBranding" element={<TheSUPREMEBranding />} key="TheSUPREMEBranding" />,
    <Route path="AdviceForAmbitious" element={<AdviceForAmbitious />} key="AdviceForAmbitious" />,
    <Route path="NobodyCares" element={<NobodyCares />} key="NobodyCares" />,
    <Route path="BettingTheFirm" element={<BettingTheFirm />} key="BettingTheFirm" />,
    <Route path="TheFactorioMindset" element={<TheFactorioMindset />} key="" />,
    <Route path="TheFactorioMindset" element={<TheFactorioMindset />} key="" />,
    <Route path="CovidStoleOurTime" element={<CovidStoleOurTime />} key="CovidStoleOurTime" />,
    <Route path="CloneCulture" element={<CloneCulture />} key="CloneCulture" />,
    <Route path="CompetingToWinDeals" element={<CompetingToWinDeals />} key="CompetingToWinDeals" />,
    <Route path="SoftLaunchAMobileGame" element={<SoftLaunchAMobileGame />} key="SoftLaunchAMobileGame" />,
    <Route path="LessonsFromYear29" element={<LessonsFromYear29 />} key="LessonsFromYear29" />,
    <Route path="VentureCapitalInWeb3" element={<VentureCapitalInWeb3 />} key="VentureCapitalInWeb3" />,
    <Route path="DecadesAreShort" element={<DecadesAreShort />} key="DecadesAreShort" />,
    <Route path="ReturnToFundamentals" element={<ReturnToFundamentals />} key="ReturnToFundamentals" />,
    <Route path="TheCurrentThing" element={<TheCurrentThing />} key="TheCurrentThing" />,
    <Route path="CryptoGamingIsNotTheFuture" element={<CryptoGamingIsNotTheFuture />} key="CryptoGamingIsNotTheFuture" />,
    <Route path="SeeingOnlyTheQuestions" element={<SeeingOnlyTheQuestions />} key="SeeingOnlyTheQuestions" />,
    <Route path="InsideFacebookMarketplace" element={<InsideFacebookMarketplace />} key="InsideFacebookMarketplace" />,
    <Route path="MentalModelExamples" element={<MentalModelExamples />} key="MentalModelExamples" />,
    <Route path="Soulbound" element={<Soulbound />} key="Soulbound" />,
    <Route path="TheSmartestWebsite" element={<TheSmartestWebsite />} key="TheSmartestWebsite" />,
    <Route path="TeslaMasterPlan" element={<TeslaMasterPlan />} key="TeslaMasterPlan" />,
    <Route path="UserEngagement" element={<UserEngagement />} key="UserEngagement" />,
    <Route path="ZhangYiming" element={<ZhangYiming />} key="ZhangYiming" />,
    <Route path="TheStoryOfTFT" element={<TheStoryOfTFT />} key="TheStoryOfTFT" />,
    <Route path="SortByControversial" element={<SortByControversial />} key="SortByControversial" />,
]