import { Route } from "react-router-dom"
import {TheSmartestWebsite, MeasureYourLife, TheMiracleYear, BettingOnUnknownUnknowns, LessonsOnProductMarketFit, DiversificationResultsInMediocrity, PricingNicheProducts,
        TheGreatUPS, OnlyThingThatMatters, MasterPlanTesla, SurvivorIoCaseStudy, YoutubeCoolhunters, BattlePasses, TimSweeneyTalks, TimeAnxiety, ImpossiblyUseless, GotMyBrainBack, 
        InternetHasBroadenedCareer, ThePonziCareer, SpeculationIsASuperpower, StartupIdeasDumbest, YourIdeaIsWorthless, TheDayOneFan, TheSUPREMEBranding, AdviceForAmbitious, NobodyCares, 
        BettingTheFirm, TheFactorioMindset, CovidStoleOurTime, CloneCulture, CompetingToWinDeals, SoftLaunchAMobileGame, LessonsFromYear29, VentureCapitalInWeb3, DecadesAreShort, ReturnToFundamentals, 
        TheCurrentThing, CryptoGamingIsNotTheFuture, SeeingOnlyTheQuestions, InsideFacebookMarketplace, MentalModelExamples, Soulbound, TeslaMasterPlan, UserEngagement, ZhangYiming} from "./ArticleComponents22"
import { SortByControversial, TheStoryOfTFT } from "./ArticleComponents23"


export default  [
    <Route path="MeasureYourLife" element={<MeasureYourLife />}  />,
    <Route path="TheMiracleYear" element={<TheMiracleYear />}  />,
    <Route path="BettingOnUnknownUnknowns" element={<BettingOnUnknownUnknowns />}  />,
    <Route path="LessonsOnProductMarketFit" element={<LessonsOnProductMarketFit />}  />,
    <Route path="DiversificationResultsInMediocrity" element={<DiversificationResultsInMediocrity />}  />,
    <Route path="PricingNicheProducts" element={<PricingNicheProducts />}  />,
    <Route path="TheGreatUPS" element={<TheGreatUPS />}  />,
    <Route path="OnlyThingThatMatters" element={<OnlyThingThatMatters />}  />,
    <Route path="MasterPlanTesla" element={<MasterPlanTesla />}  />,
    <Route path="SurvivorIoCaseStudy" element={<SurvivorIoCaseStudy />}  />,
    <Route path="YoutubeCoolhunters" element={<YoutubeCoolhunters />}  />,
    <Route path="TheSmartestWebsite" element={<TheSmartestWebsite />}  />,
    <Route path="BattlePasses" element={<BattlePasses />}  />,
    <Route path="TimSweeneyTalks" element={<TimSweeneyTalks />}  />,
    <Route path="TimeAnxiety" element={<TimeAnxiety />}  />,
    <Route path="ImpossiblyUseless" element={<ImpossiblyUseless />}  />,
    <Route path="GotMyBrainBack" element={<GotMyBrainBack />}  />,
    <Route path="InternetHasBroadenedCareer" element={<InternetHasBroadenedCareer />}  />,
    <Route path="ThePonziCareer" element={<ThePonziCareer />}  />,
    <Route path="SpeculationIsASuperpower" element={<SpeculationIsASuperpower />}  />,
    <Route path="StartupIdeasDumbest" element={<StartupIdeasDumbest />}  />,
    <Route path="YourIdeaIsWorthless" element={<YourIdeaIsWorthless />}  />,
    <Route path="TheDayOneFan" element={<TheDayOneFan />}  />,
    <Route path="TheSUPREMEBranding" element={<TheSUPREMEBranding />}  />,
    <Route path="AdviceForAmbitious" element={<AdviceForAmbitious />}  />,
    <Route path="NobodyCares" element={<NobodyCares />}  />,
    <Route path="BettingTheFirm" element={<BettingTheFirm />}  />,
    <Route path="TheFactorioMindset" element={<TheFactorioMindset />}  />,
    <Route path="CovidStoleOurTime" element={<CovidStoleOurTime />}  />,
    <Route path="CloneCulture" element={<CloneCulture />}  />,
    <Route path="CompetingToWinDeals" element={<CompetingToWinDeals />}  />,
    <Route path="SoftLaunchAMobileGame" element={<SoftLaunchAMobileGame />}  />,
    <Route path="LessonsFromYear29" element={<LessonsFromYear29 />}  />,
    <Route path="VentureCapitalInWeb3" element={<VentureCapitalInWeb3 />}  />,
    <Route path="DecadesAreShort" element={<DecadesAreShort />}  />,
    <Route path="ReturnToFundamentals" element={<ReturnToFundamentals />}  />,
    <Route path="TheCurrentThing" element={<TheCurrentThing />}  />,
    <Route path="CryptoGamingIsNotTheFuture" element={<CryptoGamingIsNotTheFuture />}  />,
    <Route path="SeeingOnlyTheQuestions" element={<SeeingOnlyTheQuestions />}  />,
    <Route path="InsideFacebookMarketplace" element={<InsideFacebookMarketplace />}  />,
    <Route path="MentalModelExamples" element={<MentalModelExamples />}  />,
    <Route path="Soulbound" element={<Soulbound />}  />,
    <Route path="TheSmartestWebsite" element={<TheSmartestWebsite />}  />,
    <Route path="TeslaMasterPlan" element={<TeslaMasterPlan />}  />,
    <Route path="UserEngagement" element={<UserEngagement />}  />,
    <Route path="ZhangYiming" element={<ZhangYiming />}  />,

    <Route path="TheStoryOfTFT" element={<TheStoryOfTFT />}  />,
<Route path="SortByControversial" element={<SortByControversial />}  />,
]